version: "3.9"
services:
  node:
    build:
      context: .
      #dockerfile: mycustomdockerfile
    ports: 
      - "3000:3000"
    links:
      - mongus
    volumes:
      - .:/home/app
  mongus:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nico
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
      # mysql:/var/lib/mysql
      # postgres:/var/lib/postgresql/data
volumes:
  mongo-data:
